## MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: root

  jpa:
    hibernate:
      use-new-id-generator-mappings: false

# drop n create table, good for testing, comment this in production
      ddl-auto: update
